version: '3'
services:
  evolution-api:
    image: atendai/evolution-api:v1.8.7
    container_name: evolution-api
    ports:
      - "8089:8080"
    environment:
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - AUTHENTICATION_API_KEY=${API_KEY}
    volumes:
      - evolution_instances:/evolution/instances
    restart: unless-stopped

  whatsapp-validator:
    image: python:3.11-slim
    container_name: whatsapp-validator
    command: >
      sh -c "pip install --no-cache-dir flask flask-socketio pyTelegramBotAPI python-dotenv requests &&
             python app.py"
    ports:
      - "5050:5000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - validator_data:/app
    working_dir: /app
    restart: unless-stopped
    pull_policy: always

volumes:
  evolution_instances:
  validator_data: